<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-ETBT7MC" failures="0" tests="1" name="TestNg_Assignments.Assign_157_Forcefailure_Testcase" time="1.040" errors="1" timestamp="2025-05-19T18:34:51 IST" skipped="0">
  <testcase classname="TestNg_Assignments.Assign_157_Forcefailure_Testcase" name="forcefailure" time="1.040">
    <error message="Method TestNg_Assignments.Assign_157_Forcefailure_Testcase.forcefailure() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNg_Assignments.Assign_157_Forcefailure_Testcase.forcefailure() didn't finish within the time-out 1000
at java.base/java.lang.ProcessImpl.waitForTimeoutInterruptibly(Native Method)
at java.base/java.lang.ProcessImpl.waitFor(ProcessImpl.java:604)
at org.openqa.selenium.os.ExternalProcess.waitFor(ExternalProcess.java:291)
at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:144)
at org.openqa.selenium.manager.SeleniumManager.getBinaryPaths(SeleniumManager.java:254)
at org.openqa.selenium.remote.service.DriverFinder.getBinaryPaths(DriverFinder.java:102)
at org.openqa.selenium.remote.service.DriverFinder.getDriverPath(DriverFinder.java:55)
at org.openqa.selenium.edge.EdgeDriver.generateExecutor(EdgeDriver.java:71)
at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:60)
at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:56)
at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:48)
at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:44)
at TestNg_Assignments.Assign_157_Forcefailure_Testcase.forcefailure(Assign_157_Forcefailure_Testcase.java:9)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- forcefailure -->
</testsuite> <!-- TestNg_Assignments.Assign_157_Forcefailure_Testcase -->
